# Generated by Django 3.1.3 on 2020-11-27 04:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Associations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('associated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='agents.agents')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='leads.leads', unique=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-associated_at'],
            },
        ),
    ]
